[project]
name = "fast-med-q"
version = "0.1.0"
description = "Be faster in medical queue! Modern safe and fast Python only."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "psycopg2-binary>=2.9.10",
    "sqlmodel>=0.0.22",
    "streamlit>=1.41.1",
]

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "pylint>=3.3.3",
    "python-dotenv>=1.0.1",
    "ruff>=0.8.5",
]
